Repository ildaneta/make-crypto-mobile-hackathon, pull requests merged in 2021-11, with the labels that each got.

#8 feat: description text created
  Project_Name/codebase/App.tsx
  Project_Name/codebase/src/components/Text/index.tsx
  Project_Name/codebase/src/components/index.ts
  Project_Name/codebase/src/styles/fontsFamily.ts
  Project_Name/codebase/src/utils/enum.ts
Labels: component

#14 Feature/tag
  Project_Name/codebase/src/components/Tag/index.tsx
  Project_Name/codebase/src/components/Tag/style.ts
  Project_Name/codebase/src/components/index.ts
Labels: component

#24 feat: author component created, font problem fixed
  Project_Name/codebase/App.tsx
  Project_Name/codebase/src/components/Author/index.tsx
  Project_Name/codebase/src/components/Author/styles.ts
  Project_Name/codebase/src/components/index.ts
Labels: component

#20 Feature/pill button
  Project_Name/Readme.md
  Project_Name/codebase/App.tsx
  Project_Name/codebase/assets/celo.svg
  Project_Name/codebase/assets/coinbase.svg
  Project_Name/codebase/assets/metamask.svg
  Project_Name/codebase/assets/trust-wallet.svg
  Project_Name/codebase/src/components/PillButton/index.tsx
  Project_Name/codebase/src/components/PillButton/styles.ts
  Project_Name/codebase/src/components/Text/index.tsx
Labels: component

#27 feat: nft component created, author refactor and tag size refactor
  Project_Name/codebase/assets/heart-filled.svg
  Project_Name/codebase/assets/heart.svg
  Project_Name/codebase/src/components/Author/index.tsx
  Project_Name/codebase/src/components/Author/styles.ts
  Project_Name/codebase/src/components/Nft/index.tsx
  Project_Name/codebase/src/components/Nft/styles.ts
  Project_Name/codebase/src/components/Tag/style.ts
Labels: component

#32 refactor: nft types updated, value passed to root, and tags changed t…
  Project_Name/codebase/src/components/Nft/index.tsx
Labels: component

#35 feature/menu
  Project_Name/codebase/App.tsx
  Project_Name/codebase/assets/heart-focused.svg
  Project_Name/codebase/assets/heart-menu.svg
  Project_Name/codebase/assets/home-focused.svg
  Project_Name/codebase/assets/home.svg
  Project_Name/codebase/assets/plus-focused.svg
  Project_Name/codebase/assets/plus-menu.svg
  Project_Name/codebase/assets/profile-focused.svg
  Project_Name/codebase/assets/profile.svg
  Project_Name/codebase/assets/wallet-focused.svg
  Project_Name/codebase/assets/wallet.svg
  Project_Name/codebase/ios/Podfile.lock
  Project_Name/codebase/package.json
  Project_Name/codebase/src/components/Nft/index.tsx
  Project_Name/codebase/src/routes/bottomTabs.routes.tsx
  Project_Name/codebase/src/screens/CreateNFT/index.tsx
  Project_Name/codebase/src/screens/CreateNFT/styles.ts
  Project_Name/codebase/src/screens/DescriptionNFT/index.tsx
  Project_Name/codebase/src/screens/DescriptionNFT/styles.ts
  Project_Name/codebase/src/screens/Favorites/index.tsx
  Project_Name/codebase/src/screens/Favorites/styles.ts
  Project_Name/codebase/src/screens/Home/index.tsx
  Project_Name/codebase/src/screens/Home/styles.ts
  Project_Name/codebase/src/screens/Profile/index.tsx
  Project_Name/codebase/src/screens/Profile/styles.ts
  Project_Name/codebase/src/screens/Wallet/index.tsx
  Project_Name/codebase/src/screens/Wallet/styles.ts
  Project_Name/codebase/src/styles/fontsFamily.ts
  Project_Name/codebase/yarn.lock
Labels: component

#36 Feature/nft page
  Project_Name/codebase/src/components/BidCard/styles.ts
  Project_Name/codebase/src/components/Likes/index.tsx
  Project_Name/codebase/src/components/Likes/styles.ts
  Project_Name/codebase/src/components/Nft/styles.ts
  Project_Name/codebase/src/components/Tag/index.tsx
  Project_Name/codebase/src/components/Tag/styles.ts
  Project_Name/codebase/src/screens/DescriptionNft/index.tsx
  Project_Name/codebase/src/screens/DescriptionNft/styles.ts
  Project_Name/codebase/src/styles/dimensions.ts
  Project_Name/codebase/src/utils/enum.ts
Labels: screen

#38 Feature/modal
  Project_Name/codebase/assets/celo.svg
  Project_Name/codebase/assets/close.svg
  Project_Name/codebase/assets/coinbase.svg
  Project_Name/codebase/assets/metamask.svg
  Project_Name/codebase/assets/trust-wallet.svg
  Project_Name/codebase/src/components/InputBid/styles.ts
  Project_Name/codebase/src/components/Modal/index.tsx
  Project_Name/codebase/src/components/Modal/styles.ts
  Project_Name/codebase/src/components/UnderlineInput/index.tsx
  Project_Name/codebase/src/components/UnderlineInput/style.ts
  Project_Name/codebase/src/components/index.ts
  Project_Name/codebase/src/screens/ConnectWallet/index.tsx
  Project_Name/codebase/src/screens/ConnectWallet/styles.ts
  Project_Name/codebase/src/screens/DescriptionNFT/index.tsx
  Project_Name/codebase/src/screens/Home/index.tsx
  Project_Name/codebase/src/screens/ModalPlaceABid/index.tsx
  Project_Name/codebase/src/screens/ModalPlaceABid/styles.ts
  Project_Name/codebase/src/services/api.ts
  Project_Name/codebase/src/styles/dimensions.ts
  Project_Name/codebase/src/utils/enum.ts
Labels: component

#47 Feature/create nft
  Project_Name/codebase/assets/bid.svg
  Project_Name/codebase/assets/hand-ether.svg
  Project_Name/codebase/assets/tag.svg
  Project_Name/codebase/assets/time-ending.svg
  Project_Name/codebase/assets/up-arrow.svg
  Project_Name/codebase/src/components/SellTypesButton/index.tsx
  Project_Name/codebase/src/components/SellTypesButton/styles.ts
  Project_Name/codebase/src/components/SellTypesList/index.tsx
  Project_Name/codebase/src/components/SellTypesList/styles.ts
  Project_Name/codebase/src/components/UnderlineInput/index.tsx
  Project_Name/codebase/src/components/UnderlineInput/style.ts
  Project_Name/codebase/src/components/index.ts
  Project_Name/codebase/src/routes/stackTabs.routes.tsx
  Project_Name/codebase/src/screens/CreateNFT/index.tsx
  Project_Name/codebase/src/screens/CreateNFT/styles.ts
  Project_Name/codebase/src/screens/Home/index.tsx
  Project_Name/codebase/src/styles/colors.ts
  Project_Name/codebase/src/styles/dimensions.ts
  Project_Name/codebase/src/utils/enum.ts
Labels: screen

#54 Feature/favorites
  Project_Name/codebase/assets/empty-favorites.svg
  Project_Name/codebase/package.json
  Project_Name/codebase/src/routes/bottomTabs.routes.tsx
  Project_Name/codebase/src/screens/CreateNFT/index.tsx
  Project_Name/codebase/src/screens/Favorites/index.tsx
  Project_Name/codebase/src/screens/Favorites/styles.ts
  Project_Name/codebase/src/screens/Profile/index.tsx
  Project_Name/codebase/src/utils/enum.ts
Labels: screen

#60 feat: navigate created, walktrough text changed
  Project_Name/codebase/src/routes/bottomTabs.routes.tsx
  Project_Name/codebase/src/screens/Home/index.tsx
  Project_Name/codebase/src/screens/Walkthrough/index.tsx
Labels: refactor
